#!/bin/bash

# 更新 mkdocs 中的 index.md 文档和图片

readmd_fn="README.md"
mkdocs_content_dn="docs"

cp ${readmd_fn} ${mkdocs_content_dn}/index.md


git_update(){
    BRANCH=$(git branch --show-current)
    git status --short --branch
    echo
    git add ${mkdocs_content_dn}
    git commit -m "update mkdocs content"
    echo
}


update_num(){
    update_md_num=$(git status --short --branch | grep "docs/" | wc -l)

    if [[ $update_md_num -eq 0 ]]; then
        echo -e "\ndocs content is latest."
    else
        echo -e "\ndocs content is updated."
        git_update
    fi

    cd - > /dev/null 2>&1 
}


update_num
